#

In [3]:
import numpy as np 
import pandas  as pd

In [4]:
data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["Rudra", "Aman", "Priya", "Rahul", "Neha"],
    "Age": [21, 22, 20, 23, 21],
    "Course": ["BCA", "BCA", "BBA", "B.Tech", "BCA"],
    "Marks": [85, 90, 78, 88, 92],
    "Passed": [True, True, True, True, True]
}
df = pd.DataFrame(data)
print(df)

   Student_ID   Name  Age  Course  Marks  Passed
0         101  Rudra   21     BCA     85    True
1         102   Aman   22     BCA     90    True
2         103  Priya   20     BBA     78    True
3         104  Rahul   23  B.Tech     88    True
4         105   Neha   21     BCA     92    True

In [5]:
df[["Name"]]

    Name
0  Rudra
1   Aman
2  Priya
3  Rahul
4   Neha

In [6]:
df["desc"] = [1,2,3,3,4]

In [7]:
print(df)

   Student_ID   Name  Age  Course  Marks  Passed  desc
0         101  Rudra   21     BCA     85    True     1
1         102   Aman   22     BCA     90    True     2
2         103  Priya   20     BBA     78    True     3
3         104  Rahul   23  B.Tech     88    True     3
4         105   Neha   21     BCA     92    True     4

In [8]:
df.drop("desc" , axis= 1, inplace = True)

In [9]:
print(df)

   Student_ID   Name  Age  Course  Marks  Passed
0         101  Rudra   21     BCA     85    True
1         102   Aman   22     BCA     90    True
2         103  Priya   20     BBA     78    True
3         104  Rahul   23  B.Tech     88    True
4         105   Neha   21     BCA     92    True

In [10]:
df.loc[0]

Student_ID      101
Name          Rudra
Age              21
Course          BCA
Marks            85
Passed         True
Name: 0, dtype: object

In [11]:
df.loc[[0,1]][['Name']]

    Name
0  Rudra
1   Aman

In [14]:
df[df["Age"] < 22]

   Student_ID   Name  Age Course  Marks  Passed
0         101  Rudra   21    BCA     85    True
2         103  Priya   20    BBA     78    True
4         105   Neha   21    BCA     92    True