In [1]:
import pandas as pd
import numpy as np

In [2]:
import pandas as pd

df1 = pd.DataFrame({
    "Emp_ID": [101, 102, 103, 104],
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Department": ["HR", "IT", "Finance", "Sales"]
})

print(df1)

   Emp_ID     Name Department
0     101    Alice         HR
1     102      Bob         IT
2     103  Charlie    Finance
3     104    David      Sales

In [3]:
df2 = pd.DataFrame({
    "Emp_ID": [101, 102, 103, 105],
    "Salary": [50000, 65000, 70000, 55000]
})

print(df2)

   Emp_ID  Salary
0     101   50000
1     102   65000
2     103   70000
3     105   55000

In [7]:
pd.merge(df1,df2, on="Emp_ID",how='inner')

   Emp_ID     Name Department  Salary
0     101    Alice         HR   50000
1     102      Bob         IT   65000
2     103  Charlie    Finance   70000

In [8]:
pd.merge(df1,df2, on="Emp_ID",how='outer')

   Emp_ID     Name Department   Salary
0     101    Alice         HR  50000.0
1     102      Bob         IT  65000.0
2     103  Charlie    Finance  70000.0
3     104    David      Sales      NaN
4     105      NaN        NaN  55000.0

In [9]:
pd.merge(df1,df2, on="Emp_ID",how='left')

   Emp_ID     Name Department   Salary
0     101    Alice         HR  50000.0
1     102      Bob         IT  65000.0
2     103  Charlie    Finance  70000.0
3     104    David      Sales      NaN

In [10]:
pd.merge(df1,df2, on="Emp_ID",how='right')

   Emp_ID     Name Department  Salary
0     101    Alice         HR   50000
1     102      Bob         IT   65000
2     103  Charlie    Finance   70000
3     105      NaN        NaN   55000

In [12]:
pd.concat([df1,df2],axis= 0)

   Emp_ID     Name Department   Salary
0     101    Alice         HR      NaN
1     102      Bob         IT      NaN
2     103  Charlie    Finance      NaN
3     104    David      Sales      NaN
0     101      NaN        NaN  50000.0
1     102      NaN        NaN  65000.0
2     103      NaN        NaN  70000.0
3     105      NaN        NaN  55000.0

In [13]:
pd.concat([df1,df2],axis= 1)

   Emp_ID     Name Department  Emp_ID  Salary
0     101    Alice         HR     101   50000
1     102      Bob         IT     102   65000
2     103  Charlie    Finance     103   70000
3     104    David      Sales     105   55000

In [14]:
df1.join(df2)

ValueError: columns overlap but no suffix specified: Index(['Emp_ID'], dtype='object')

In [15]:
df3 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, 30, 28, 35]
}, index=[1, 2, 3, 4])

In [18]:
df4 = pd.DataFrame({
    "City": ["Delhi", "Mumbai", "Pune", "Jaipur"],
    "Salary": [50000, 60000, 55000, 70000]
}, index=[1, 2, 3, 5])

In [19]:
df3.join(df4)

      Name  Age    City   Salary
1    Alice   25   Delhi  50000.0
2      Bob   30  Mumbai  60000.0
3  Charlie   28    Pune  55000.0
4    David   35     NaN      NaN