In [30]:
import numpy as np
import pandas as pd

In [31]:

df = pd.DataFrame({
    "A": [1, np.nan, 3],
    "B": [np.nan, 5, 6],
    "C": [7, 8, np.nan],
    "D": [np.nan, 10, 11]
})

df = pd.DataFrame(data)

print(df)

      Name   Age     City   Salary
0    Alice  25.0    Delhi  50000.0
1      Bob   NaN   Mumbai  60000.0
2  Charlie  30.0     None      NaN
3    David  28.0  Chennai  55000.0
4      Eva   NaN  Kolkata  62000.0

In [32]:
df.isna().any()

Name      False
Age        True
City       True
Salary     True
dtype: bool

In [33]:
df.dropna()

    Name   Age     City   Salary
0  Alice  25.0    Delhi  50000.0
3  David  28.0  Chennai  55000.0

In [34]:
df.dropna(thresh=2)
# minimum 2 not nul value oni chaiye

      Name   Age     City   Salary
0    Alice  25.0    Delhi  50000.0
1      Bob   NaN   Mumbai  60000.0
2  Charlie  30.0     None      NaN
3    David  28.0  Chennai  55000.0
4      Eva   NaN  Kolkata  62000.0

In [35]:
df.fillna(0)

      Name   Age     City   Salary
0    Alice  25.0    Delhi  50000.0
1      Bob   0.0   Mumbai  60000.0
2  Charlie  30.0        0      0.0
3    David  28.0  Chennai  55000.0
4      Eva   0.0  Kolkata  62000.0

values = {"A":none,"B":0,"C":none,"D":0}
df.fillna(value=value)

In [36]:
values = {"A":8,"B":0,"C":28,"D":344}
df.fillna(value=values)

      Name   Age     City   Salary
0    Alice  25.0    Delhi  50000.0
1      Bob   NaN   Mumbai  60000.0
2  Charlie  30.0     None      NaN
3    David  28.0  Chennai  55000.0
4      Eva   NaN  Kolkata  62000.0